export default {
  'activityBar.background': '#282c34',
  'activityBar.foreground': '#d7dae0',
  'activityBarBadge.background': '#4d78cc',
  'activityBarBadge.foreground': '#f8fafd',
  'badge.background': '#282c34',
  'button.background': '#404754',
  'debugToolBar.background': '#21252b',
  'diffEditor.insertedTextBackground': '#00809b33',
  'dropdown.background': '#21252b',
  'dropdown.border': '#21252b',
  'editor.background': '#282c34',
  'editor.findMatchBackground': '#42557b',
  'editor.findMatchBorder': '#457dff',
  'editor.findMatchHighlightBackground': '#6199ff2f',
  'editor.foreground': '#abb2bf',
  'editor.lineHighlightBackground': '#2c313c',
  'editor.selectionBackground': '#67769660',
  'editor.selectionHighlightBackground': '#ffffff10',
  'editor.selectionHighlightBorder': '#dddddd',
  'editor.wordHighlightBackground': '#d2e0ff2f',
  'editor.wordHighlightBorder': '#7f848e',
  'editor.wordHighlightStrongBackground': '#abb2bf26',
  'editor.wordHighlightStrongBorder': '#7f848e',
  'editorActiveLineNumber.foreground': '#737984',
  'editorBracketMatch.background': '#515a6b',
  'editorBracketMatch.border': '#515a6b',
  'editorCursor.background': '#ffffffc9',
  'editorCursor.foreground': '#528bff',
  'editorError.foreground': '#c24038',
  'editorGroup.background': '#181a1f',
  'editorGroup.border': '#181a1f',
  'editorGroupHeader.tabsBackground': '#21252b',
  'editorHoverWidget.background': '#21252b',
  'editorHoverWidget.border': '#181a1f',
  'editorIndentGuide.activeBackground': '#c8c8c859',
  'editorIndentGuide.background': '#3b4048',
  'editorLineNumber.foreground': '#495162',
  'editorMarkerNavigation.background': '#21252b',
  'editorRuler.foreground': '#abb2bf26',
  'editorSuggestWidget.background': '#21252b',
  'editorSuggestWidget.border': '#181a1f',
  'editorSuggestWidget.selectedBackground': '#2c313a',
  'editorWarning.foreground': '#d19a66',
  'editorWhitespace.foreground': '#3b4048',
  'editorWidget.background': '#21252b',
  focusBorder: '#464646',
  'input.background': '#1d1f23',
  'list.activeSelectionBackground': '#2c313a',
  'list.activeSelectionForeground': '#d7dae0',
  'list.focusBackground': '#383e4a',
  'list.highlightForeground': '#c5c5c5',
  'list.hoverBackground': '#292d35',
  'list.inactiveSelectionBackground': '#2c313a',
  'list.inactiveSelectionForeground': '#d7dae0',
  'list.warningForeground': '#d19a66',
  'menu.foreground': '#c8c8c8',
  'peekViewEditor.background': '#1b1d23',
  'peekViewEditor.matchHighlightBackground': '#29244b',
  'peekViewResult.background': '#22262b',
  'scrollbarSlider.activeBackground': '#747d9180',
  'scrollbarSlider.background': '#4e566660',
  'scrollbarSlider.hoverBackground': '#5a637580',
  'sideBar.background': '#21252b',
  'sideBarSectionHeader.background': '#282c34',
  'statusBar.background': '#21252b',
  'statusBar.debuggingBackground': '#7e0097',
  'statusBar.debuggingBorder': '#66017a',
  'statusBar.debuggingForeground': '#ffffff',
  'statusBar.foreground': '#9da5b4',
  'statusBar.noFolderBackground': '#21252b',
  'statusBarItem.hoverBackground': '#2c313a',
  'statusBarItem.remoteBackground': '#4d78cc',
  'statusBarItem.remoteForeground': '#f8fafd',
  'tab.activeBackground': '#282c34',
  'tab.activeForeground': '#dcdcdc',
  'tab.border': '#181a1f',
  'tab.hoverBackground': '#323842',
  'tab.inactiveBackground': '#21252b',
  'tab.unfocusedHoverBackground': '#323842',
  'terminal.ansiBlack': '#2d3139',
  'terminal.ansiBlue': '#61afef',
  'terminal.ansiBrightBlack': '#7f848e',
  'terminal.ansiBrightBlue': '#528bff',
  'terminal.ansiBrightCyan': '#56b6c2',
  'terminal.ansiBrightGreen': '#98c379',
  'terminal.ansiBrightMagenta': '#7e0097',
  'terminal.ansiBrightRed': '#f44747',
  'terminal.ansiBrightWhite': '#d7dae0',
  'terminal.ansiBrightYellow': '#e5c07b',
  'terminal.ansiCyan': '#56b6c2',
  'terminal.ansiGreen': '#98c379',
  'terminal.ansiMagenta': '#c678dd',
  'terminal.ansiRed': '#e06c75',
  'terminal.ansiWhite': '#d7dae0',
  'terminal.ansiYellow': '#e5c07b',
  'terminal.foreground': '#c8c8c8',
  'textLink.foreground': '#61afef',
  'titleBar.activeBackground': '#282c34',
  'titleBar.activeForeground': '#9da5b4',
  'titleBar.inactiveBackground': '#21252b',
  'titleBar.inactiveForeground': '#6b717d'
  // "activityBar.activeBorder": "#d7dae0",
  // "activityBar.dropBackground": "#ffffff1f",
  // "activityBar.inactiveForeground": "#d7dae066",
  // "badge.foreground": "#ffffff",
  // "breadcrumb.activeSelectionForeground": "#e0e0e0",
  // "breadcrumb.background": "#282c34",
  // "breadcrumb.focusForeground": "#e0e0e0",
  // "breadcrumb.foreground": "#cccccccc",
  // "breadcrumbPicker.background": "#21252b",
  // "button.foreground": "#ffffff",
  // "button.hoverBackground": "#4d5565",
  // "checkbox.background": "#21252b",
  // "checkbox.border": "#21252b",
  // "checkbox.foreground": "#f0f0f0",
  // "dart.closingLabels": "#dcdcdc80",
  // "debugExceptionWidget.background": "#420b0d",
  // "debugExceptionWidget.border": "#a31515",
  // "debugIcon.continueForeground": "#75beff",
  // "debugIcon.disconnectForeground": "#f48771",
  // "debugIcon.pauseForeground": "#75beff",
  // "debugIcon.restartForeground": "#89d185",
  // "debugIcon.startForeground": "#89d185",
  // "debugIcon.stepIntoForeground": "#75beff",
  // "debugIcon.stepOutForeground": "#75beff",
  // "debugIcon.stepOverForeground": "#75beff",
  // "debugIcon.stopForeground": "#f48771",
  // "descriptionForeground": "#ccccccb3",
  // "diffEditor.removedTextBackground": "#ff000033",
  // "dropdown.foreground": "#f0f0f0",
  // "editor.findRangeHighlightBackground": "#3a3d4166",
  // "editor.focusedStackFrameHighlightBackground": "#7abd7a4d",
  // "editor.hoverHighlightBackground": "#264f7840",
  // "editor.inactiveSelectionBackground": "#67769630",
  // "editor.lineHighlightBorder": "#282828",
  // "editor.rangeHighlightBackground": "#ffffff0b",
  // "editor.snippetFinalTabstopHighlightBorder": "#525252",
  // "editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
  // "editor.stackFrameHighlightBackground": "#ffff0033",
  // "editorCodeLens.foreground": "#999999",
  // "editorGroup.dropBackground": "#53595d80",
  // "editorGroupHeader.noTabsBackground": "#282c34",
  // "editorGutter.addedBackground": "#587c0c",
  // "editorGutter.background": "#282c34",
  // "editorGutter.commentRangeForeground": "#c5c5c5",
  // "editorGutter.deletedBackground": "#94151b",
  // "editorGutter.modifiedBackground": "#0c7d9d",
  // "editorHint.foreground": "#eeeeeeb3",
  // "editorHoverWidget.foreground": "#cccccc",
  // "editorHoverWidget.statusBarBackground": "#282c34",
  // "editorInfo.foreground": "#75beff",
  // "editorLightBulb.foreground": "#ffcc00",
  // "editorLightBulbAutoFix.foreground": "#75beff",
  // "editorLineNumber.activeForeground": "#737984",
  // "editorLink.activeForeground": "#4e94ce",
  // "editorMarkerNavigationError.background": "#c24038",
  // "editorMarkerNavigationInfo.background": "#75beff",
  // "editorMarkerNavigationWarning.background": "#d19a66",
  // "editorOverviewRuler.addedForeground": "#007acc99",
  // "editorOverviewRuler.border": "#7f7f7f4d",
  // "editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
  // "editorOverviewRuler.commonContentForeground": "#60606066",
  // "editorOverviewRuler.currentContentForeground": "#40c8ae80",
  // "editorOverviewRuler.deletedForeground": "#007acc99",
  // "editorOverviewRuler.errorForeground": "#ff1212b3",
  // "editorOverviewRuler.findMatchForeground": "#d186167e",
  // "editorOverviewRuler.incomingContentForeground": "#40a6ff80",
  // "editorOverviewRuler.infoForeground": "#75beff",
  // "editorOverviewRuler.modifiedForeground": "#007acc99",
  // "editorOverviewRuler.rangeHighlightForeground": "#007acc99",
  // "editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
  // "editorOverviewRuler.warningForeground": "#d19a66",
  // "editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
  // "editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
  // "editorPane.background": "#282c34",
  // "editorSuggestWidget.foreground": "#abb2bf",
  // "editorSuggestWidget.highlightForeground": "#c5c5c5",
  // "editorUnnecessaryCode.opacity": "#000000aa",
  // "editorWidget.border": "#454545",
  // "editorWidget.foreground": "#cccccc",
  // "errorForeground": "#f48771",
  // "extensionBadge.remoteBackground": "#4d78cc",
  // "extensionBadge.remoteForeground": "#f8fafd",
  // "extensionButton.prominentBackground": "#327e36",
  // "extensionButton.prominentForeground": "#ffffff",
  // "extensionButton.prominentHoverBackground": "#28632b",
  // "foreground": "#cccccc",
  // "gitDecoration.addedResourceForeground": "#81b88b",
  // "gitDecoration.conflictingResourceForeground": "#6c6cc4",
  // "gitDecoration.deletedResourceForeground": "#c74e39",
  // "gitDecoration.ignoredResourceForeground": "#8c8c8c",
  // "gitDecoration.modifiedResourceForeground": "#e2c08d",
  // "gitDecoration.submoduleResourceForeground": "#8db9e2",
  // "gitDecoration.untrackedResourceForeground": "#73c991",
  // "gitlens.gutterBackgroundColor": "#ffffff13",
  // "gitlens.gutterForegroundColor": "#bebebe",
  // "gitlens.gutterUncommittedForegroundColor": "#00bcf299",
  // "gitlens.lineHighlightBackgroundColor": "#00bcf233",
  // "gitlens.lineHighlightOverviewRulerColor": "#00bcf299",
  // "gitlens.trailingLineBackgroundColor": "#00000000",
  // "gitlens.trailingLineForegroundColor": "#99999959",
  // "icon.foreground": "#c5c5c5",
  // "imagePreview.border": "#80808059",
  // "input.foreground": "#cccccc",
  // "input.placeholderForeground": "#cccccc80",
  // "inputOption.activeBackground": "#46464680",
  // "inputOption.activeBorder": "#007acc00",
  // "inputValidation.errorBackground": "#5a1d1d",
  // "inputValidation.errorBorder": "#be1100",
  // "inputValidation.infoBackground": "#063b49",
  // "inputValidation.infoBorder": "#007acc",
  // "inputValidation.warningBackground": "#352a05",
  // "inputValidation.warningBorder": "#b89500",
  // "list.dropBackground": "#383e4a",
  // "list.errorForeground": "#f88070",
  // "list.filterMatchBackground": "#6199ff2f",
  // "list.invalidItemForeground": "#b89500",
  // "listFilterWidget.background": "#653723",
  // "listFilterWidget.noMatchesOutline": "#be1100",
  // "listFilterWidget.outline": "#00000000",
  // "menu.background": "#21252b",
  // "menu.selectionBackground": "#2c313a",
  // "menu.selectionForeground": "#d7dae0",
  // "menu.separatorBackground": "#bbbbbb",
  // "menubar.selectionBackground": "#ffffff1a",
  // "menubar.selectionForeground": "#9da5b4",
  // "merge.commonContentBackground": "#60606029",
  // "merge.commonHeaderBackground": "#60606066",
  // "merge.currentContentBackground": "#40c8ae33",
  // "merge.currentHeaderBackground": "#40c8ae80",
  // "merge.incomingContentBackground": "#40a6ff33",
  // "merge.incomingHeaderBackground": "#40a6ff80",
  // "minimap.findMatchHighlight": "#d18616",
  // "minimap.selectionHighlight": "#264f78",
  // "notificationCenterHeader.background": "#2b3038",
  // "notificationLink.foreground": "#61afef",
  // "notifications.background": "#21252b",
  // "notifications.border": "#2b3038",
  // "notifications.foreground": "#cccccc",
  // "notificationsErrorIcon.foreground": "#c24038",
  // "notificationsInfoIcon.foreground": "#75beff",
  // "notificationsWarningIcon.foreground": "#d19a66",
  // "panel.background": "#282c34",
  // "panel.border": "#80808059",
  // "panel.dropBackground": "#ffffff1f",
  // "panelTitle.activeBorder": "#e7e7e7",
  // "panelTitle.activeForeground": "#e7e7e7",
  // "panelTitle.inactiveForeground": "#e7e7e799",
  // "peekView.border": "#007acc",
  // "peekViewEditorGutter.background": "#1b1d23",
  // "peekViewResult.fileForeground": "#ffffff",
  // "peekViewResult.lineForeground": "#bbbbbb",
  // "peekViewResult.matchHighlightBackground": "#ea5c004d",
  // "peekViewResult.selectionBackground": "#3399ff33",
  // "peekViewResult.selectionForeground": "#ffffff",
  // "peekViewTitle.background": "#1e1e1e",
  // "peekViewTitleDescription.foreground": "#ccccccb3",
  // "peekViewTitleLabel.foreground": "#ffffff",
  // "pickerGroup.border": "#3f3f46",
  // "pickerGroup.foreground": "#3794ff",
  // "problemsErrorIcon.foreground": "#c24038",
  // "problemsInfoIcon.foreground": "#75beff",
  // "problemsWarningIcon.foreground": "#d19a66",
  // "progressBar.background": "#0e70c0",
  // "quickInput.background": "#21252b",
  // "scrollbar.shadow": "#000000",
  // "settings.checkboxBackground": "#21252b",
  // "settings.checkboxBorder": "#21252b",
  // "settings.checkboxForeground": "#f0f0f0",
  // "settings.dropdownBackground": "#21252b",
  // "settings.dropdownBorder": "#21252b",
  // "settings.dropdownForeground": "#f0f0f0",
  // "settings.dropdownListBorder": "#454545",
  // "settings.headerForeground": "#e7e7e7",
  // "settings.modifiedItemIndicator": "#0c7d9d",
  // "settings.numberInputBackground": "#1d1f23",
  // "settings.numberInputForeground": "#cccccc",
  // "settings.textInputBackground": "#1d1f23",
  // "settings.textInputForeground": "#cccccc",
  // "sideBar.dropBackground": "#ffffff1f",
  // "statusBar.noFolderForeground": "#9da5b4",
  // "statusBarItem.activeBackground": "#ffffff2e",
  // "statusBarItem.prominentBackground": "#00000080",
  // "statusBarItem.prominentForeground": "#9da5b4",
  // "statusBarItem.prominentHoverBackground": "#0000004d",
  // "symbolIcon.arrayForeground": "#cccccc",
  // "symbolIcon.booleanForeground": "#cccccc",
  // "symbolIcon.classForeground": "#ee9d28",
  // "symbolIcon.colorForeground": "#cccccc",
  // "symbolIcon.constantForeground": "#cccccc",
  // "symbolIcon.constructorForeground": "#b180d7",
  // "symbolIcon.enumeratorForeground": "#ee9d28",
  // "symbolIcon.enumeratorMemberForeground": "#75beff",
  // "symbolIcon.eventForeground": "#ee9d28",
  // "symbolIcon.fieldForeground": "#75beff",
  // "symbolIcon.fileForeground": "#cccccc",
  // "symbolIcon.folderForeground": "#cccccc",
  // "symbolIcon.functionForeground": "#b180d7",
  // "symbolIcon.interfaceForeground": "#75beff",
  // "symbolIcon.keyForeground": "#cccccc",
  // "symbolIcon.keywordForeground": "#cccccc",
  // "symbolIcon.methodForeground": "#b180d7",
  // "symbolIcon.moduleForeground": "#cccccc",
  // "symbolIcon.namespaceForeground": "#cccccc",
  // "symbolIcon.nullForeground": "#cccccc",
  // "symbolIcon.numberForeground": "#cccccc",
  // "symbolIcon.objectForeground": "#cccccc",
  // "symbolIcon.operatorForeground": "#cccccc",
  // "symbolIcon.packageForeground": "#cccccc",
  // "symbolIcon.propertyForeground": "#cccccc",
  // "symbolIcon.referenceForeground": "#cccccc",
  // "symbolIcon.snippetForeground": "#cccccc",
  // "symbolIcon.stringForeground": "#cccccc",
  // "symbolIcon.structForeground": "#cccccc",
  // "symbolIcon.textForeground": "#cccccc",
  // "symbolIcon.typeParameterForeground": "#cccccc",
  // "symbolIcon.unitForeground": "#cccccc",
  // "symbolIcon.variableForeground": "#75beff",
  // "tab.activeModifiedBorder": "#3399cc",
  // "tab.inactiveForeground": "#dcdcdc80",
  // "tab.inactiveModifiedBorder": "#3399cc80",
  // "tab.unfocusedActiveBackground": "#282c34",
  // "tab.unfocusedActiveForeground": "#dcdcdc80",
  // "tab.unfocusedActiveModifiedBorder": "#3399cc80",
  // "tab.unfocusedInactiveForeground": "#dcdcdc40",
  // "tab.unfocusedInactiveModifiedBorder": "#3399cc40",
  // "terminal.background": "#282c34",
  // "terminal.border": "#80808059",
  // "terminal.selectionBackground": "#ffffff40",
  // "textBlockQuote.background": "#7f7f7f1a",
  // "textBlockQuote.border": "#007acc80",
  // "textCodeBlock.background": "#0a0a0a66",
  // "textLink.activeForeground": "#3794ff",
  // "textPreformat.foreground": "#d7ba7d",
  // "textSeparator.foreground": "#ffffff2e",
  // "tree.indentGuidesStroke": "#585858",
  // "widget.shadow": "#000000"
}
